---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: egenintres-se
spec:
  secretName: egenintres-se-tls
  duration: 160h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - egenintres.se
    - "*.egenintres.se"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  usages:
    - digital signature
