---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      vaultwarden:
        containers:
          app:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.37.2
            env:
              - name: DOMAIN
                value: https://vw.egenintres.se
              - name: TZ
                value: Europe/Stockholm
              - name: SIGNUPS_ALLOWED
                value: "false"
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-database-secret
                    key: DATABASE_URL
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
