---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: jellyfin
  values:
    controllers:
      jellyfin:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.10
            env:
              - name: TZ
                value: Europe/Stockholm
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096
    persistence:
      config:
        existingClaim: jellyfin
        globalMounts:
          - path: /config
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
      media:
        existingClaim: media
        globalMounts:
          - path: /media
