---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      zigbee2mqtt:
        containers:
          app:
            image:
              repository: koenkk/zigbee2mqtt
              tag: 2.13.0
            env:
              - name: TZ
                value: Europe/Stockholm
            securityContext:
              privileged: true

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      serial:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_6130242C-if01-port0
        globalMounts:
          - path: /dev/ttyACM1
