---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: sabnzbd
  values:
    controllers:
      sabnzbd:
        pod:
          dnsConfig:
            options:
              - name: ndots
                value: "1"
        containers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.1
            envFrom:
              - secretRef:
                  name: gluetun
            env:
              - name: FIREWALL_OUTBOUND_SUBNETS
                value: 10.42.0.0/24,10.43.0.0/16
              - name: BLOCK_MALICIOUS
                value: "off"
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
          app:
            image:
              repository: ghcr.io/linuxserver/sabnzbd
              tag: 5.0.4
            env:
              - name: TZ
                value: Europe/Stockholm
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080
    persistence:
      config:
        existingClaim: sabnzbd
        globalMounts:
          - path: /config
      downloads:
        existingClaim: downloads
        globalMounts:
          - path: /downloads
