---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gluetun
    creationPolicy: Owner
  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: /gluetun/VPN_SERVICE_PROVIDER
    - secretKey: VPN_TYPE
      remoteRef:
        key: /gluetun/VPN_TYPE
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: /gluetun/WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: /gluetun/WIREGUARD_ADDRESSES
    - secretKey: SERVER_CITIES
      remoteRef:
        key: /gluetun/SERVER_CITIES
