---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-database
  namespace: default
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/default/home-assistant/database
  prune: true
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: home-assistant-database
      VOLSYNC_SCHEDULE: "15 2 * * *"
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_RUNASUSER: "999"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: default
spec:
  dependsOn:
    - name: home-assistant-database
    - name: zigbee2mqtt
    - name: zwavejs
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/default/home-assistant/app
  prune: true
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: home-assistant
      VOLSYNC_SCHEDULE: "04 1 * * *"
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_RUNASUSER: "0"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto
  namespace: default
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/default/home-assistant/mosquitto
  prune: true
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: mosquitto
      VOLSYNC_SCHEDULE: "42 3 * * *"
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_RUNASUSER: "1000"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  dependsOn:
    - name: mosquitto
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/default/home-assistant/zigbee2mqtt
  prune: true
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: zigbee2mqtt
      VOLSYNC_SCHEDULE: "05 0 * * *"
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_RUNASUSER: "1000"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zwavejs
  namespace: default
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/default/home-assistant/zwavejs
  prune: true
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: zwavejs
      VOLSYNC_SCHEDULE: "23 3 * * *"
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_RUNASUSER: "0"

