---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dbackup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: dbackup-secret
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: /dbackup/ENCRYPTION_KEY
    - secretKey: BETTER_AUTH_URL
      remoteRef:
        key: /dbackup/BETTER_AUTH_URL
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: /dbackup/BETTER_AUTH_SECRET
