---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: alfred
  namespace: external-services
  labels:
    kubernetes.io/service-name: alfred
addressType: IPv4
ports:
  - name: http
    port: 8337
    protocol: TCP
endpoints:
  - addresses:
      # External service reachable by IP only (no FQDN yet)
      - 192.168.1.141
