---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: renovate-secret
    creationPolicy: Owner
  data:
    - secretKey: mendRnvLicenseKey
      remoteRef:
        key: /renovate/MEND_RNV_LICENSE_KEY
    - secretKey: mendRnvGithubAppId
      remoteRef:
        key: /renovate/MEND_RNV_GITHUB_APP_ID
    - secretKey: mendRnvGithubAppKey
      remoteRef:
        key: /renovate/MEND_RNV_GITHUB_APP_KEY
    - secretKey: mendRnvGithubBotUserId
      remoteRef:
        key: /renovate/MEND_RNV_GITHUB_BOT_USER_ID
    - secretKey: mendRnvWebhookSecret
      remoteRef:
        key: /renovate/MEND_RNV_WEBHOOK_SECRET
    - secretKey: githubComToken
      remoteRef:
        key: /renovate/GITHUB_COM_TOKEN
