---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-dst
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${APP}-volsync-restic
    destinationPVC: ${APP}
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    accessModes:
      - ReadWriteOnce
    capacity: ${VOLSYNC_CAPACITY:=5Gi}
    storageClassName: ${VOLSYNC_STORAGECLASS:=longhorn}
    volumeSnapshotClassName: ${VOLSYNC_VOLUMESNAPSHOTCLASS:=longhorn}
    moverSecurityContext:
      runAsUser: ${VOLSYNC_RUNASUSER:=0}
