---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: /authentik/AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: /authentik/AUTHENTIK_POSTGRESQL__PASSWORD

