---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: crowdsec
    creationPolicy: Owner
  data:
    - secretKey: ENROLL_KEY
      remoteRef:
        key: /crowdsec/ENROLL_KEY
    - secretKey: ENROLL_INSTANCE_NAME
      remoteRef:
        key: /crowdsec/ENROLL_INSTANCE_NAME
