---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: crowdsec
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: crowdsec-agent
            patch: |-
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: crowdsec-agent
              spec:
                template:
                  spec:
                    initContainers:
                      - name: wait-for-lapi-and-register
                        command:
                          - sh
                          - -c
                          - >-
                            if [ -f /tmp_config/local_api_credentials.yaml ]; then
                            echo "already registered; reusing credentials"; exit 0;
                            fi;
                            until nc "$LAPI_HOST" "$LAPI_PORT" -z; do
                            echo waiting for lapi to start; sleep 5; done;
                            ln -s /staging/etc/crowdsec /etc/crowdsec &&
                            cscli lapi register --machine "$USERNAME" -u "$LAPI_URL"
                            --token "$REGISTRATION_TOKEN" &&
                            cp /etc/crowdsec/local_api_credentials.yaml
                            /tmp_config/local_api_credentials.yaml
  values:
    container_runtime: containerd
    agent:
      acquisition:
        - namespace: network
          podName: envoy-network-envoy-gateway-local-*
          program: envoy
          poll_without_inotify: true
        - namespace: network
          podName: envoy-network-envoy-gateway-public-*
          program: envoy
          poll_without_inotify: true
        - namespace: default
          podName: vaultwarden-*
          program: vaultwarden
          poll_without_inotify: true
      env:
        - name: COLLECTIONS
          value: >-
            crowdsecurity/http-extended-context
            crowdsecurity/http-dos
            crowdsecurity/http-cve
            yanis-kouidri/envoy
            Dominic-Wagner/vaultwarden
    lapi:
      env:
        - name: ENROLL_KEY
          valueFrom:
            secretKeyRef:
              name: crowdsec
              key: ENROLL_KEY
        - name: ENROLL_INSTANCE_NAME
          valueFrom:
            secretKeyRef:
              name: crowdsec
              key: ENROLL_INSTANCE_NAME
        - name: ENROLL_TAGS
          value: "k8s linux prod"
    config:
      config.yaml.local: |-
        api:
          client:
            # the log processor will remove delete itself from LAPI when stopping.
            unregister_on_exit: true
          server:
            # This is needed for agent autoregistration
            auto_registration: # Activate if not using TLS for authentication
              enabled: true
              token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
              allowed_ranges: # /!\ Make sure to adapt to the pod IP ranges used by your cluster
                - "127.0.0.1/32"
                - "192.168.0.0/22"
                - "10.42.0.0/24"
                - "10.43.0.0/16"

