---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage/ks.yaml
  - headlamp/ks.yaml
  - dozzle/ks.yaml
  - authentik/ks.yaml
  - jellyfin/ks.yaml
  - sabnzbd/ks.yaml
  - sonarr/ks.yaml
  - radarr/ks.yaml
  - profilarr/ks.yaml
  - prowlarr/ks.yaml
  - seerr/ks.yaml
  - immich/ks.yaml
  - securitypolicy.yaml
