---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app seerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      seerr:
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.4.1
            env:
              - name: TZ
                value: Europe/Stockholm
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5055
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/config
