---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vaultwarden-database-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MARIADB_ROOT_PASSWORD: "{{ .MARIADB_ROOT_PASSWORD }}"
        MARIADB_PASSWORD: "{{ .MARIADB_PASSWORD }}"
        MARIADB_DATABASE: "{{ .MARIADB_DATABASE }}"
        MARIADB_USER: "{{ .MARIADB_USER }}"
        DATABASE_URL: "mysql://{{ .MARIADB_USER }}:{{ .MARIADB_PASSWORD }}@vaultwarden-database:3306/{{ .MARIADB_DATABASE }}"
  data:
    - secretKey: MARIADB_ROOT_PASSWORD
      remoteRef:
        key: /vaultwarden/MARIADB_ROOT_PASSWORD
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: /vaultwarden/MARIADB_PASSWORD
    - secretKey: MARIADB_DATABASE
      remoteRef:
        key: /vaultwarden/MARIADB_DATABASE
    - secretKey: MARIADB_USER
      remoteRef:
        key: /vaultwarden/MARIADB_USER
