---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-admin-creds
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: /kube-prometheus-stack/GRAFANA_ADMIN_USER
    - secretKey: admin-password
      remoteRef:
        key: /kube-prometheus-stack/GRAFANA_ADMIN_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: /kube-prometheus-stack/GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /kube-prometheus-stack/GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    - secretKey: GF_AUTH_GENERIC_OAUTH_AUTH_URL
      remoteRef:
        key: /kube-prometheus-stack/GF_AUTH_GENERIC_OAUTH_AUTH_URL
    - secretKey: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
      remoteRef:
        key: /kube-prometheus-stack/GF_AUTH_GENERIC_OAUTH_TOKEN_URL
