---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  values:
    grafana:
      envFromSecret: grafana
      grafana.ini:
        server:
          root_url: https://grafana.egenintres.se
        "auth.generic_oauth":
          enabled: true
          name: Authentik
          allow_sign_up: true
          scopes: openid profile email groups
      admin:
        existingSecret: grafana-admin-creds
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: false
      service:
        type: ClusterIP

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: longhorn
              resources:
                requests:
                  storage: 50Gi
        retention: 30d

    alertmanager:
      enabled: true
