services:
  app:
    container_name: doco-cd
    # You can also pin to a specific tag (version)
    # Available tags can be found here: https://github.com/kimdre/doco-cd/pkgs/container/doco-cd
    image: ghcr.io/kimdre/doco-cd:latest
    restart: unless-stopped
    ports:
      - "80:80" # Webhook endpoint
      - "9120:9120" # Prometheus metrics
    # For all available environment variables and explanations, see https://github.com/kimdre/doco-cd/wiki/App-Settings
    environment:
      TZ: Europe/Stockholm
      POLL_CONFIG_FILE: /poll-config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      # The data volume (left side) can also be replaced with a bind mount to a local directory, for example:
      # - ./data:/data
      - data:/data
      - ./poll-config.yaml:/poll-config.yaml:ro,Z
    cap_drop:
      - ALL
    security_opt:
      - label:disable
    healthcheck:
      test: [ "CMD", "/doco-cd", "healthcheck" ]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  data: