---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 1h
  chart:
    spec:
      chart: headlamp
      version: 0.42.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
  values:
    httpRoute:
      enabled: true
      parentRefs:
        - name: envoy-gateway-local
          namespace: network
      hostnames:
        - headlamp.lab.egenintres.se
    config:
      pluginsDir: /build/plugins
      sessionTTL: 604800
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
