---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: renovate-operator-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          renovate-operator.mogenius.com/allow-ref: "true"
  data:
    - secretKey: APP_ID
      remoteRef:
        key: /renovate/APP_ID
    - secretKey: INSTALL_ID
      remoteRef:
        key: /renovate/INSTALL_ID
    - secretKey: PEM
      remoteRef:
        key: /renovate/PEM
    - secretKey: webhook-token
      remoteRef:
        key: /renovate/WEBHOOK_TOKEN
    - secretKey: GITHUB_COM_TOKEN
      remoteRef:
        key: /renovate/GITHUB_COM_TOKEN
    - secretKey: RENOVATE_HOST_RULES
      remoteRef:
        key: /renovate/RENOVATE_HOST_RULES
