---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      mealie:
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.25.0
            env:
              - name: TZ
                value: Europe/Stockholm
              - name: BASE_URL
                value: https://mealie.egenintres.se
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: DEFAULT_GROUP
                value: Default
              - name: DEFAULT_HOUSEHOLD
                value: Family
              - name: ALLOW_SIGNUP
                value: "false"
              - name: MAX_WORKERS
                value: "1"
              - name: WEB_CONCURRENCY
                value: "1"
              - name: OIDC_AUTH_ENABLED
                value: "true"
              - name: OIDC_SIGNUP_ENABLED
                value: "true"
              - name: OIDC_CONFIGURATION_URL
                value: "https://auth.egenintres.se/application/o/mealie/.well-known/openid-configuration"
              - name: OIDC_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: OIDC_CLIENT_SECRET
              - name: OIDC_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: OIDC_CLIENT_ID
              - name: OIDC_PROVIDER_NAME
                value: "Authentik"
              - name: OIDC_REMEMBER_ME
                value: "true"
              - name: OIDC_AUTO_REDIRECT
                value: "true"
              - name: OIDC_USER_CLAIM
                value: "preferred_username"
              - name: OIDC_ADMIN_GROUP
                value: "Mealie Admins"
              - name: OIDC_USER_GROUP
                value: "Mealie Users"
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9000
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
