---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      home-assistant:
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2026.8.0
            env:
              - name: TZ
                value: Europe/Stockholm
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8123
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      configuration:
        type: configMap
        name: home-assistant-config
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
      secrets:
        type: secret
        name: home-assistant-secret
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
