---
when:
  - event: cron
    cron: renovate
  - event: manual
variables:
  log_level: info
steps:
  - name: renovate
    image: ghcr.io/renovatebot/renovate:latest@sha256:8079b1b65950bed71562469f28777b523b97895aa64ced5b0d0a69878124cd7f
    environment:
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ENDPOINT: https://codeberg.org/api/v1
      RENOVATE_REPOSITORIES: Jaeensson/homeops
      RENOVATE_TOKEN:
        from_secret: renovate_token
      RENOVATE_GITHUB_COM_TOKEN:
        from_secret: github_token
      LOG_LEVEL: ${log_level}
