---
when:
  - event: cron
    cron: renovate
  - event: manual
variables:
  log_level: info
steps:
  - name: renovate
    image: ghcr.io/renovatebot/renovate:latest@sha256:47421f2f3f82048e969b5195dd808d5ac2c5f69d43d192191c4a3dca390afe06
    environment:
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ENDPOINT: https://codeberg.org/api/v1
      RENOVATE_REPOSITORIES: Jaeensson/homeops
      RENOVATE_TOKEN:
        from_secret: renovate_token
      RENOVATE_GITHUB_COM_TOKEN:
        from_secret: github_token
      LOG_LEVEL: ${log_level}
