---
depends_on:
  - validate

when:
  - event: cron
    cron: renovate
  - event: push
    branch:
      - renovate/**
  - event: manual

variables:
  log_level: info
steps:
  - name: generate-token
    image: ghcr.io/yyewolf/woodpecker-plugins/github-app-token:latest@sha256:60911352fdd062b35fe757c40b5de52b7180ad68af230210a2b3e667f60adb0c
    environment:
      PLUGIN_GITHUB_APP_ID:
        from_secret: renovate_app_id
      PLUGIN_GITHUB_PRIVATE_KEY_PEM:
        from_secret: renovate_private_key
      PLUGIN_GITHUB_INSTALLATION_ID:
        from_secret: renovate_installation_id
      PLUGIN_OUTPUT_FILE: .github_token
  - name: renovate
    image: ghcr.io/renovatebot/renovate:latest@sha256:0e3778f0de0a627e87f1764d961455583efba7c63fc4b8ec15d073a23f582e62
    environment:
      RENOVATE_PLATFORM: github
      RENOVATE_REPOSITORIES: Jaeensson/homeops
      RENOVATE_GIT_AUTHOR:
        from_secret: renovate_git_author
      RENOVATE_GITHUB_COM_TOKEN:
        from_secret: github_token
      LOG_LEVEL: ${log_level}
    commands:
      - export RENOVATE_TOKEN=$(cat .github_token)
      - renovate
