---
when:
  - event: push
    branch:
      - renovate/**

steps:
  - name: validate-renovate-config
    image: ghcr.io/renovatebot/renovate:44.7.2
    commands:
      - renovate-config-validator --strict .renovaterc.json5

  - name: check-yaml-format
    image: ghcr.io/google/yamlfmt:0.21.0
    commands:
      - yamlfmt -verbose -lint kubernetes/

  - name: terraform-lint
    image: ghcr.io/terraform-linters/tflint:v0.64.0
    commands:
      - tflint --chdir terraform --recursive

  - name: flux-local-test
    image: ghcr.io/allenporter/flux-local:v8.4.0
    environment:
      GIT_CONFIG_COUNT: 1
      GIT_CONFIG_KEY_0: safe.directory
      GIT_CONFIG_VALUE_0: "*"
    commands:
      - flux-local test --path kubernetes/flux/ --all-namespaces -v
