---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dozzle
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dozzle
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
    controllers:
      dozzle:
        serviceAccount:
          name: pod-viewer
        containers:
          app:
            image:
              repository: amir20/dozzle
              tag: v10.6.5@sha256:fa12525776bf665147d82bf031ff262ee89a0a12454122558a353ec38ada4aaf
            env:
              DOZZLE_MODE: k8s
    service:
      app:
        controller: dozzle
        ports:
          http:
            port: 8080
