---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dozzle
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dozzle
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
    controllers:
      dozzle:
        serviceAccount:
          name: pod-viewer
        containers:
          app:
            image:
              repository: amir20/dozzle
              tag: v10.6.15@sha256:5bb13e26b62f9bc4bd390e3e0c9423263b7df86e3a4167b718cc6e352f96b54f
            env:
              DOZZLE_MODE: k8s
    service:
      app:
        controller: dozzle
        ports:
          http:
            port: 8080
