---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dozzle
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dozzle
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
    controllers:
      dozzle:
        serviceAccount:
          name: pod-viewer
        containers:
          app:
            image:
              repository: amir20/dozzle
              tag: v10.6.2@sha256:dac897ce93cbc0db48d9a6014ba24fb9438edc95c27e283a6fcc9260ea474d6d
            env:
              DOZZLE_MODE: k8s
    service:
      app:
        controller: dozzle
        ports:
          http:
            port: 8080
