---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: woodpecker
  values:
    server:
      env:
        WOODPECKER_HOST: "https://woodpecker.lab.egenintres.se"
        WOODPECKER_GITHUB: "true"
        WOODPECKER_OPEN: "false"
        WOODPECKER_ADMIN: "Jaeensson"
        WOODPECKER_FORCE_IGNORE_SERVICE_FAILURE: "false"
      extraSecretNamesForEnvFrom:
        - woodpecker-default-agent-secret
      createAgentSecret: false
      persistentVolume:
        enabled: false
      extraVolumes:
        - name: data
          persistentVolumeClaim:
            claimName: woodpecker-server
      extraVolumeMounts:
        - name: data
          mountPath: /var/lib/woodpecker
    agent:
      enabled: true
      replicaCount: 1
      env:
        WOODPECKER_SERVER: "woodpecker-server.woodpecker-system.svc.cluster.local:9000"
        WOODPECKER_BACKEND_K8S_NAMESPACE: woodpecker-system
        WOODPECKER_BACKEND_K8S_STORAGE_RWX: "false"
        WOODPECKER_CONNECT_RETRY_COUNT: "10"
      extraSecretNamesForEnvFrom:
        - woodpecker-default-agent-secret
      persistence:
        enabled: true
        existingClaim: woodpecker-agent
