---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: woodpecker
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.6.3@sha256:a83a31565f93a4b69784179141396d71f96cee97c88c30dc3c2ad984219bbfbd
  url: oci://ghcr.io/woodpecker-ci/helm/woodpecker
