# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: pihole
  data:
    - secretKey: FTLCONF_webserver_api_password
      remoteRef:
        key: /pihole/FTLCONF_webserver_api_password
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
