---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: &name pihole
  values:
    controllers:
      pihole:
        containers:
          app:
            image:
              repository: ghcr.io/pi-hole/pihole
              tag: 2026.07.2@sha256:f7d1be836e3bc608b56d82fc9904f5a831cdfbc0dc9c6d58f94e4c985c70038b
            env:
              - name: TZ
                value: Europe/Stockholm
              - name: PIHOLE_UID
                value: "0"
              - name: PIHOLE_GID
                value: "0"
              - name: DNSMASQ_USER
                value: root
              - name: FTLCONF_dns_listeningMode
                value: all
            envFrom:
              - secret: *name
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_ADMIN
                  - SYS_TIME
                  - SYS_NICE
                  - SETGID
                  - SETUID
                  - CHOWN
    service:
      app:
        controller: *name
        ports:
          http:
            port: 80
      dns:
        annotations:
          metallb.io/loadBalancerIPs: 192.168.2.1
        controller: *name
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
    persistence:
      config:
        existingClaim: *name
        globalMounts:
          - path: /etc/pihole
